# Generated by Django 2.0.4 on 2018-08-10 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180804_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('DIRECTOR', 'DIRECTOR'), ('ACTOR', 'ACTOR'), ('PRODUCER', 'PRODUCER'), ('CAMERA_MAN', 'CAMERA_MAN'), ('SCREENPLAY_WRITER', 'SCREENPLAY_WRITER'), ('ASST_DIRECTOR', 'ASST_DIRECTOR')], default='DIRECTOR', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile no should be valid', regex='^[6789]\\d{9}$')]),
        ),
    ]
